config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  
  resources :welcome do 
   collection do
        get :export_file
        get :import_file
      end
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
 has_attached_file :avatar#, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :avatar, :content_type => %w(image/jpeg image/jpg image/png)
end

app/models/user.rb
require 'csv'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.to_csv
    attributes = %w{id email first_name last_name name}

    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end
        
  def name
    "#{first_name} #{last_name}"
  end
       
  def self.insert_data file
  	CSV.foreach(file.path, :headers => true) do |row|
	  User.new(row.to_hash)
	  p row.to_hash
	end
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  

  protected


    def configure_permitted_parameters
	   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name,:last_name, :email, :password) }
	   devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:first_name, :last_name, :email, :password, :remember_me) }
	   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name,:last_name, :email, :password, :password_confirmation,:reset_password_token,:current_password) }
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@users = User.all
  	respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end

  def create
    @user = Document.create( doc_params )  if params[:user_doc].present?
    redirect_to root_url
  end

  def export_file
  	respond_to do |format|
      format.html
      format.csv { send_data User.to_csv, filename: "users-#{Time.now}.csv" }
    end
  end

  private
	def doc_params
	  unless params[:user_doc][:avatar].content_type == "text/csv"
      params.require(:user_doc).permit(:avatar)
    else
       User.insert_data params[:user_doc][:avatar]
    end 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%#= link_to "import_file", import_file_welcome_index_path %>
<%= link_to "CSV", export_file_welcome_index_path(format: "csv") %>

<%= form_for :user_doc, url: welcome_index_path, html: { multipart: true } do |form| %>
<%= form.file_field :avatar %>
<%= form.submit "submit" %>
  
<% end %>,